CREATE TABLE IF NOT EXISTS plans (
  id SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  goal TEXT NOT NULL,
  resources TEXT NOT NULL,
  constraints TEXT NOT NULL,
  generated_plan TEXT NOT NULL,
  tasks JSONB,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

